extends: default

rules:
  document-start: disable
  line-length: disable
  trailing-spaces: disable
  truthy:
    check-keys: false
  comments:
    min-spaces-from-content: 1
  empty-lines:
    max-end: 1
