[build-system]
requires = ["setuptools>=61", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "xfuser"
description = "A Scalable Inference Engine for Diffusion Transformers (DiTs) on Multiple Computing Devices"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "xDiT Team", email = "fangjiarui123@gmail.com" },
]
dynamic = ["version"]
dependencies = [
    "torch>=2.4.1",
    "accelerate>=0.33.0",
    "transformers>=4.39.1",
    "sentencepiece>=0.1.99",
    "beautifulsoup4>=4.12.3",
    "distvae>=0.1.0",
    "yunchang>=0.6.0",
    "einops",
    "diffusers>=0.33.0",
    "av",
    "peft",
    "numpy",
]

[project.optional-dependencies]
flash-attn = [
    "flash-attn>=2.6.0",  # NOTE: flash-attn is necessary if ring_degree > 1
]
optimum-quanto = [
    "optimum-quanto",  # NOTE: optimum-quanto is necessary if use_fp8_t5_encoder is enabled
]
torchao = [
    "torchao",  # NOTE: torchao is necessary if use_fp8_gemms is enabled
]
flask = [
    "flask",  # NOTE: flask is necessary to run xDiT as an http service
]
ray = [
    "ray",  # NOTE: ray is necessary if RayDiffusionPipeline is used
]
opencv-python = [
    "opencv-python-headless",  # NOTE: opencv-python is necessary if ConsisIDPipeline is used
]
cache-dit = [
    "cache-dit>=1.5.0,<1.6.0",  # NOTE: cache-dit is required for --cache_method dbcache
]
test = [
    "pytest",
    "imageio",
    "imageio-ffmpeg",
]

[project.scripts]
xdit = "xfuser.cli:main"

[project.urls]
Homepage = "https://github.com/xdit-project/xDiT."

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools_scm]
version_file = "xfuser/__version__.py"
fallback_version = "0.0.0.dev"
write_to_source = true
version_file_template = "# file generated by setuptools-scm; do not edit manually\n__version__ = version = {version!r}\n"
